### ISSUE TITLE
使用过程中报错的问题

### ISSUE THREAD

**Issue by Mateoust** [AMEKENN/miHoYoSign#3]
.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.5.RELEASE)

2021-03-11 17:33:02.985  INFO 6756 --- [           main] com.ame.ysbbssign.YsbbssignApplication   : Starting YsbbssignApplication on ecs-sn3-medium-2-win-20200201123959 with PID 6756 (C:\Users\Administrator\Desktop\ys\ysbbssign.jar started by Administrator in C:\Users\Administrator\Desktop\ys)
2021-03-11 17:33:02.995  INFO 6756 --- [           main] com.ame.ysbbssign.YsbbssignApplication   : No active profile set, falling back to default profiles: default
2021-03-11 17:33:05.073  INFO 6756 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFERRED mode.
2021-03-11 17:33:05.288  INFO 6756 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 187ms. Found 2 JPA repository interfaces.
2021-03-11 17:33:06.980  INFO 6756 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 4440 (http)
2021-03-11 17:33:07.018  INFO 6756 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-03-11 17:33:07.019  INFO 6756 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.39]
2021-03-11 17:33:07.367  INFO 6756 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-03-11 17:33:07.367  INFO 6756 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 4194 ms
2021-03-11 17:33:08.391  INFO 6756 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-03-11 17:33:08.410  INFO 6756 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2021-03-11 17:33:08.811  INFO 6756 --- [         task-1] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2021-03-11 17:33:09.006  INFO 6756 --- [         task-1] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.22.Final
2021-03-11 17:33:09.594  INFO 6756 --- [         task-1] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2021-03-11 17:33:09.926  INFO 6756 --- [         task-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-03-11 17:33:11.560  INFO 6756 --- [         task-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-03-11 17:33:11.668  INFO 6756 --- [         task-1] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL8Dialect
2021-03-11 17:33:13.698  INFO 6756 --- [         task-1] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2021-03-11 17:33:13.708  INFO 6756 --- [         task-1] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2021-03-11 17:33:15.197  INFO 6756 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
2021-03-11 17:33:15.537  INFO 6756 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 4440 (http) with context path ''
2021-03-11 17:33:15.545  INFO 6756 --- [           main] DeferredRepositoryInitializationListener : Triggering deferred initialization of Spring Data repositories…
2021-03-11 17:33:15.545  INFO 6756 --- [           main] DeferredRepositoryInitializationListener : Spring Data repositories initialized!
2021-03-11 17:33:15.584  INFO 6756 --- [           main] com.ame.ysbbssign.YsbbssignApplication   : Started YsbbssignApplication in 14.164 seconds (JVM running for 16.156)
2021-03-11 17:33:15.764  INFO 6756 --- [nio-4440-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-03-11 17:33:15.764  INFO 6756 --- [nio-4440-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-03-11 17:33:15.784  INFO 6756 --- [nio-4440-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 10 ms
2021-03-11 17:33:15.901  INFO 6756 --- [nio-4440-exec-1] c.a.ysbbssign.controller.MiraiWebSocket  : 有新连接加入,session id:0,当前在线机器人数量为:1
Exception in thread "Thread-4" org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:416)
        at com.ame.ysbbssign.util.Utils.sendPrivateMsgByHttp(Utils.java:31)
        at com.ame.ysbbssign.service.UserService.signByUser(UserService.java:367)
        at com.ame.ysbbssign.service.UserService.lambda$sign$0(UserService.java:382)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-6" org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:416)
        at com.ame.ysbbssign.util.Utils.sendPrivateMsgByHttp(Utils.java:31)
        at com.ame.ysbbssign.service.UserService.signByUser(UserService.java:367)
        at com.ame.ysbbssign.service.UserService.lambda$sign$0(UserService.java:382)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-8" org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:416)
        at com.ame.ysbbssign.util.Utils.sendPrivateMsgByHttp(Utils.java:31)
        at com.ame.ysbbssign.service.UserService.signByUser(UserService.java:367)
        at com.ame.ysbbssign.service.UserService.lambda$sign$0(UserService.java:382)
        at java.lang.Thread.run(Unknown Source)
2021-03-14 09:50:13.451  INFO 6756 --- [nio-4440-exec-3] c.a.ysbbssign.controller.MiraiWebSocket  : QQ:[1*********5]  Message:[全部签到]
Exception in thread "Thread-10" org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:416)
        at com.ame.ysbbssign.util.Utils.sendPrivateMsgByHttp(Utils.java:31)
        at com.ame.ysbbssign.service.UserService.signByUser(UserService.java:369)
        at com.ame.ysbbssign.service.UserService.lambda$sign$0(UserService.java:382)
        at java.lang.Thread.run(Unknown Source)

日志在上方，过一段时间会报错。然后我手动签到了一次也会报错。麻烦大佬看看是什么问题，先谢过了。

系统是Win Sever 2019

Java版本是
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) Client VM (build 25.281-b09, mixed mode)

另外就是米游社接口的salt值更新了，后续大佬会继续更新吗？从隔壁[https://github.com/y1ndan/genshin-impact-helper/issues/154](url)这个issues看到的。

**Comment by AMEKENN** [comment]
你加了accessToken?

目前我自己用正常,所以懒得动就没更新

**Comment by Mateoust** [comment]
> 你加了accessToken?
> 目前我自己用正常,所以懒得动就没更新

是使用指令+手机号登录的。accessToken这个得看看数据库。你一说accessToken 就想起之前使用指令+手机号也会出现报错，会不会是这个原因导致数据库的token出错？
接口这个现在还能用。只是问问大佬后续改了会不会更进去更新? 这个QQ反馈还是挺实用的。

**Comment by Mateoust** [comment]
刚刚看了下数据库。user这个表里面的cookie都是有的
![20210314195158](https://user-images.githubusercontent.com/46558043/111067381-f1e7ec00-84fe-11eb-8008-d4e6ba4354b7.png)

**Comment by AMEKENN** [comment]
sendPrivateMsgByHttp(Utils.java:31)全是这一行报的错,发消息报401,你现在应该收不到程序的反馈消息吧,通过程序登录米游社的两个步骤都是有成功失败反馈的

**Comment by Mateoust** [comment]
> sendPrivateMsgByHttp(Utils.java:31)全是这一行报的错,发消息报401,你现在应该收不到程序的反馈消息吧,通过程序登录米游社的两个步骤都是有成功失败反馈的

第一次输入指令+手机号的时候后台有一个报错。然后我那个群友重复试了几次。后续的几次成功了，然后去go-cqhttp的消息控制台去看后续是有成功的提示的。第一次报错的时候没有消息发送。日志上那个是我手动触发“全部签到”。是可以收到正在全部签到的。但是却报错了。

**Comment by AMEKENN** [comment]
> > sendPrivateMsgByHttp(Utils.java:31)全是这一行报的错,发消息报401,你现在应该收不到程序的反馈消息吧,通过程序登录米游社的两个步骤都是有成功失败反馈的
> 
> 第一次输入指令+手机号的时候后台有一个报错。然后我那个群友重复试了几次。后续的几次成功了，然后去go-cqhttp的消息控制台去看后续是有成功的提示的。第一次报错的时候没有消息发送。日志上那个是我手动触发“全部签到”。是可以收到正在全部签到的。但是却报错了。

啊这,怎么还有随机性

**Comment by Mateoust** [comment]
> > > sendPrivateMsgByHttp(Utils.java:31)全是这一行报的错,发消息报401,你现在应该收不到程序的反馈消息吧,通过程序登录米游社的两个步骤都是有成功失败反馈的
> > 
> > 
> > 第一次输入指令+手机号的时候后台有一个报错。然后我那个群友重复试了几次。后续的几次成功了，然后去go-cqhttp的消息控制台去看后续是有成功的提示的。第一次报错的时候没有消息发送。日志上那个是我手动触发“全部签到”。是可以收到正在全部签到的。但是却报错了。
> 
> 啊这,怎么还有随机性

刚刚我尝试复现，输入指令+手机又正常回复了。我尝试了多个手机号。貌似特定的手机号还会提示“账号或密码错误”
![QQ截图20210314202725](https://user-images.githubusercontent.com/46558043/111068444-b7cd1900-8503-11eb-8d4b-96c43bc0d224.png)
![20210314202628](https://user-images.githubusercontent.com/46558043/111068407-98ce8700-8503-11eb-8320-eb33cea54309.png)

**Comment by AMEKENN** [comment]
这个返回的消息是直接用米游社返回的消息的,是米游社就这么写的,所以这个手机号应该是没有绑定米游社账号的吧,至于那个报错,网络不稳定?我自己没遇到过啊,你用cqhttp-mirai试试?

**Comment by Mateoust** [comment]
> 这个返回的消息是直接用米游社返回的消息的,是米游社就这么写的,所以这个手机号应该是没有绑定米游社账号的吧,至于那个报错,网络不稳定?我自己没遇到过啊,你用cqhttp-mirai试试?

行，我先放着看看。后续看看能不能复现了。谢谢大佬了

**Comment by Mateoust** [comment]
2021-03-22 09:34:55.475  INFO 9616 --- [io-4440-exec-10] c.a.ysbbssign.controller.MiraiWebSocket  : 有新连接加入,session id:0,当前在线机器人数量为:1
2021-03-25 08:34:16.863  INFO 9616 --- [nio-4440-exec-5] c.a.ysbbssign.controller.MiraiWebSocket  : QQ:[23*******9]  Message:[获取登录米游社的验证码:18*********9]
2021-03-25 08:35:02.296  INFO 9616 --- [nio-4440-exec-4] c.a.ysbbssign.controller.MiraiWebSocket  : QQ:[2*********9]  Message:[登录:18**********30]
2021-03-25 08:35:03.672 ERROR 9616 --- [nio-4440-exec-4] c.a.ysbbssign.controller.MiraiWebSocket  : 机器人意外掉线
org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:416)
        at com.ame.ysbbssign.util.Utils.sendGroupMsgByHttp(Utils.java:41)
        at com.ame.ysbbssign.util.Utils.sendLogToGroup(Utils.java:70)
        at com.ame.ysbbssign.service.UserService.createOrUpdateUser(UserService.java:134)
        at com.ame.ysbbssign.service.UserService$$FastClassBySpringCGLIB$$a6bd1217.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
        at com.ame.ysbbssign.service.UserService$$EnhancerBySpringCGLIB$$92f429a.createOrUpdateUser(<generated>)
        at com.ame.ysbbssign.controller.MiraiWebSocket.login(MiraiWebSocket.java:209)
        at com.ame.ysbbssign.controller.MiraiWebSocket.onMessage(MiraiWebSocket.java:118)
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:80)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:402)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:502)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)
2021-03-25 08:35:03.721  INFO 9616 --- [nio-4440-exec-4] c.a.ysbbssign.controller.MiraiWebSocket  : 有一连接关闭,session id:0,当前在线机器人数量为:0
2021-03-25 08:35:08.956  INFO 9616 --- [nio-4440-exec-3] c.a.ysbbssign.controller.MiraiWebSocket  : 有新连接加入,session id:1,当前在线机器人数量为:1
2021-03-25 08:36:27.449  INFO 9616 --- [nio-4440-exec-3] c.a.ysbbssign.controller.MiraiWebSocket  : QQ:[2*********19]  Message:[登录:18**************30]
2021-03-25 08:36:54.364  INFO 9616 --- [nio-4440-exec-5] c.a.ysbbssign.controller.MiraiWebSocket  : QQ:[2**********9]  Message:[登录:18******** *****30]
2021-03-25 08:37:11.921  INFO 9616 --- [nio-4440-exec-9] c.a.ysbbssign.controller.MiraiWebSocket  : QQ:[2**********9]  Message:[获取登录米游社的验证码:18*********9]

GO-CQHTTP日志：

[2021-03-25 08:34:16] [INFO]: 收到来自群 原神萌新(1*******8) 内 逐鹿(2*******9) 的临时会话消息: 获取登录米游社的验证码:18**********49
[2021-03-25 08:34:17] [INFO]: 发送好友 2*****19(23*****9)  的消息: 成功 (-559993381)
[2021-03-25 08:35:02] [INFO]: 收到来自群 原神萌新(1*****8) 内 逐鹿(2*****9) 的临时会话消息: 登录:18***********49 354130
[2021-03-25 08:35:03] [WARNING]: 监听反向WS API时出现错误: websocket: close 1002 (protocol error): An unrecoverable IOException occurred so the connection was closed
[2021-03-25 08:35:04] [WARNING]: 向WS服务器 127.0.0.1:4440 推送Event时出现错误: websocket: close sent
[2021-03-25 08:35:08] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:4440/ysbbssign
[2021-03-25 08:36:27] [INFO]: 收到来自群 原神萌新(10*****8) 内 逐鹿(2*****19) 的临时会话消息: 登录:18**********49354130
[2021-03-25 08:36:27] [INFO]: 发送好友 2*****19(2*****9)  的消息: 格式不正确 (1090238584)
[2021-03-25 08:36:31] [INFO]: 好友 2*****9 撤回了消息: 980893531
[2021-03-25 08:36:54] [INFO]: 收到来自群 原神萌新(10*****8) 内 逐鹿(23*****9) 的临时会话消息: 登录:18*****9 354130
[2021-03-25 08:36:54] [INFO]: 发送好友 23*****9(23*****9)  的消息: 验证码错误 (939297006)
[2021-03-25 08:37:11] [INFO]: 收到来自群 原神萌新(10*****28) 内 逐鹿(2*****19) 的临时会话消息: 获取登录米游社的验证码:18*********9
[2021-03-25 08:37:12] [INFO]: 发送好友 2*****19(23*****9)  的消息: 成功 (-1359619756)



貌似登录指令会机器人意外掉线。然后自动重连。但是重连之后重试几次，功能是正常的。

**Comment by AMEKENN** [comment]
> 2021-03-22 09:34:55.475 INFO 9616 --- [io-4440-exec-10] c.a.ysbbssign.controller.MiraiWebSocket : 有新连接加入,session id:0,当前在线机器人数量为:1
> 2021-03-25 08:34:16.863 INFO 9616 --- [nio-4440-exec-5] c.a.ysbbssign.controller.MiraiWebSocket : QQ:[23_******9] Message:[获取登录米游社的验证码:18******_**9] 2021-03-25 08:35:02.296 INFO 9616 --- [nio-4440-exec-4] c.a.ysbbssign.controller.MiraiWebSocket : QQ:[2**_******9] Message:[登录:18******__**30] 2021-03-25 08:35:03.672 ERROR 9616 --- [nio-4440-exec-4] c.a.ysbbssign.controller.MiraiWebSocket : 机器人意外掉线 org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body] at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105) at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184) at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125) at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780) at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738) at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672) at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:416) at com.ame.ysbbssign.util.Utils.sendGroupMsgByHttp(Utils.java:41) at com.ame.ysbbssign.util.Utils.sendLogToGroup(Utils.java:70) at com.ame.ysbbssign.service.UserService.createOrUpdateUser(UserService.java:134) at com.ame.ysbbssign.service.UserService$$FastClassBySpringCGLIB$$a6bd1217.invoke() at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) at com.ame.ysbbssign.service.UserService$$EnhancerBySpringCGLIB$$92f429a.createOrUpdateUser() at com.ame.ysbbssign.controller.MiraiWebSocket.login(MiraiWebSocket.java:209) at com.ame.ysbbssign.controller.MiraiWebSocket.onMessage(MiraiWebSocket.java:118) at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:80) at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:402) at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119) at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:502) at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301) at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133) at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82) at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171) at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151) at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Unknown Source) 2021-03-25 08:35:03.721 INFO 9616 --- [nio-4440-exec-4] c.a.ysbbssign.controller.MiraiWebSocket : 有一连接关闭,session id:0,当前在线机器人数量为:0 2021-03-25 08:35:08.956 INFO 9616 --- [nio-4440-exec-3] c.a.ysbbssign.controller.MiraiWebSocket : 有新连接加入,session id:1,当前在线机器人数量为:1 2021-03-25 08:36:27.449 INFO 9616 --- [nio-4440-exec-3] c.a.ysbbssign.controller.MiraiWebSocket : QQ:[2**_******19] Message:[登录:18**************30] 2021-03-25 08:36:54.364 INFO 9616 --- [nio-4440-exec-5] c.a.ysbbssign.controller.MiraiWebSocket : QQ:[2**********9] Message:[登录:18******** *****30]
> 2021-03-25 08:37:11.921 INFO 9616 --- [nio-4440-exec-9] c.a.ysbbssign.controller.MiraiWebSocket : QQ:[2*_********9] Message:[获取登录米游社的验证码:18********_9]
> 
> GO-CQHTTP日志：
> 
> [2021-03-25 08:34:16] [INFO]: 收到来自群 原神萌新(1_******8) 内 逐鹿(2******_9) 的临时会话消息: 获取登录米游社的验证码:18**********49 [2021-03-25 08:34:17] [INFO]: 发送好友 2_****19(23****_9) 的消息: 成功 (-559993381) [2021-03-25 08:35:02] [INFO]: 收到来自群 原神萌新(1_****8) 内 逐鹿(2****_9) 的临时会话消息: 登录:18*_****_****49 354130 [2021-03-25 08:35:03] [WARNING]: 监听反向WS API时出现错误: websocket: close 1002 (protocol error): An unrecoverable IOException occurred so the connection was closed [2021-03-25 08:35:04] [WARNING]: 向WS服务器 127.0.0.1:4440 推送Event时出现错误: websocket: close sent [2021-03-25 08:35:08] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:4440/ysbbssign [2021-03-25 08:36:27] [INFO]: 收到来自群 原神萌新(10****_8) 内 逐鹿(2****_19) 的临时会话消息: 登录:18**********49354130
> [2021-03-25 08:36:27] [INFO]: 发送好友 2_****19(2****_9) 的消息: 格式不正确 (1090238584)
> [2021-03-25 08:36:31] [INFO]: 好友 2_****9 撤回了消息: 980893531 [2021-03-25 08:36:54] [INFO]: 收到来自群 原神萌新(10****_8) 内 逐鹿(23_****9) 的临时会话消息: 登录:18****_9 354130
> [2021-03-25 08:36:54] [INFO]: 发送好友 23_****9(23****_9) 的消息: 验证码错误 (939297006)
> [2021-03-25 08:37:11] [INFO]: 收到来自群 原神萌新(10_****28) 内 逐鹿(2****_19) 的临时会话消息: 获取登录米游社的验证码:18****_****9 [2021-03-25 08:37:12] [INFO]: 发送好友 2****_19(23*****9) 的消息: 成功 (-1359619756)
> 
> 貌似登录指令会机器人意外掉线。然后自动重连。但是重连之后重试几次，功能是正常的。

好的,我知道可能是哪里有问题了,等签到不能用的时候我修修看吧

**Comment by fack-A2Z** [comment]
大佬我在获取米游社验证码的时候，一直发送请求失败 缺少参数。是米哈游的请求方式改了吗，

**Comment by AMEKENN** [comment]
> 大佬我在获取米游社验证码的时候，一直发送请求失败 缺少参数。是米哈游的请求方式改了吗，

是的,加了滑动验证码,这个程序已经没用了,我已经大改过了,改成cookie登录米游社了,还加了崩坏3的蚊子腿,但还没发到github,懒得写教学和说明文档,所以一直拖着没发
