### ISSUE TITLE
SQLite3 The database file is locked (database is locked)

### ISSUE THREAD

**Issue by Mateoust** [AMEKENN/miHoYoSign#6]
又来麻烦大大了，为了方便又换成了sqllite3。但是遇到了`[SQLITE_BUSY]  The database file is locked (database is locked)`的问题，于是我又观察了几天。下方是3次的日志。都出现了

> 2021-07-18 06:30:08.431  WARN 6152 --- [ task-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 5, SQLState: null
> 2021-07-18 06:30:08.431 ERROR 6152 --- [ task-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : [SQLITE_BUSY]  The database file is locked (database is locked)

看了下sqlliete的文件被锁定了，这个会不会是进程1在update的时候进程2进行了操作呢？ 不知道该怎么解决。

另外在`2021-07-18 06:30:09.039  INFO 6152 --- [ task-4] c.ame.mihoyosign.service.MessageService  : -->  QQ[1053807086]  Message:[签到奖励列表已更新]`中的QQ也不是bot的账号（虽然不影响）但是想弄明白这中间发生了什么，导致的一个陌生qq号

除了 `database is locked`这个问题,还想请教一下这几个问题。

- 因为 `Mirai 的群临时消息类型不为private,而为group,不符合OneBot标准`所以要加好友。但是`go-cqhttp`是符合`onebot`协议的，是管理员的情况下支持临时会话但是我发现还是得加好友才能发送消息，这个我该怎么修改呢？

- 还有就是想问一下无论成功失败都会发送消息，但是我看了下数据库里的`notifications`是0应该是不通知才对。因为试过开启通知是1，所以有点不明白。

- 我在`application.yml`中修改了help命令的回复，但是返回的命令还是之前完整的一段，这个是怎么回事呢？有点奇怪

**最后多有打扰了，非常感谢！**

```
2021-07-15 09:44:56.684  INFO 7988 --- [nio-4440-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 10 ms
2021-07-15 09:44:56.801  INFO 7988 --- [nio-4440-exec-1] c.a.m.controller.MiraiWebSocket          : 已连接mirai
当前运行的线程名称：task-2
当前运行的线程名称：task-3
2021-07-16 06:30:08.172 ERROR 7988 --- [         task-3] o.hibernate.id.enhanced.TableStructure   : HHH000376: Could not updateQuery hi value in: hibernate_sequence

org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:1010) ~[sqlite-jdbc-3.31.1.jar!/:na]
        at org.sqlite.core.DB.newSQLException(DB.java:1022) ~[sqlite-jdbc-3.31.1.jar!/:na]
        at org.sqlite.core.DB.execute(DB.java:861) ~[sqlite-jdbc-3.31.1.jar!/:na]
        at org.sqlite.core.DB.executeUpdate(DB.java:902) ~[sqlite-jdbc-3.31.1.jar!/:na]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98) ~[sqlite-jdbc-3.31.1.jar!/:na]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-3.4.5.jar!/:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar!/:na]
        at org.hibernate.id.enhanced.TableStructure.executeUpdate(TableStructure.java:205) ~[hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.id.enhanced.TableStructure.access$900(TableStructure.java:46) ~[hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.id.enhanced.TableStructure$1$1.execute(TableStructure.java:163) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.id.enhanced.TableStructure$1$1.execute(TableStructure.java:126) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.jdbc.WorkExecutor.executeReturningWork(WorkExecutor.java:55) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.jdbc.AbstractReturningWork.accept(AbstractReturningWork.java:34) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcIsolationDelegate.delegateWork(JdbcIsolationDelegate.java:57) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.id.enhanced.TableStructure$1.getNextValue(TableStructure.java:125) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.id.enhanced.NoopOptimizer.generate(NoopOptimizer.java:40) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.id.enhanced.SequenceStyleGenerator.generate(SequenceStyleGenerator.java:523) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:115) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:185) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:128) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:55) [hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102) ~[hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:720) ~[hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:706) ~[hibernate-core-5.4.25.Final.jar!/:5.4.25.Final]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_291]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_291]
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:314) ~[spring-orm-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at com.sun.proxy.$Proxy84.persist(Unknown Source) ~[na:na]
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:554) ~[spring-data-jpa-2.3.6.RELEASE.jar!/:2.3.6.RELEASE]
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.saveAll(SimpleJpaRepository.java:588) ~[spring-data-jpa-2.3.6.RELEASE.jar!/:2.3.6.RELEASE]
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.saveAll(SimpleJpaRepository.java:78) ~[spring-data-jpa-2.3.6.RELEASE.jar!/:2.3.6.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_291]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_291]
        at org.springframework.data.repository.core.support.ImplementationInvocationMetadata.invoke(ImplementationInvocationMetadata.java:72) ~[spring-data-commons-2.3.6.RELEASE.jar!/:2.3.6.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:382) ~[spring-data-commons-2.3.6.RELEASE.jar!/:2.3.6.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:205) ~[spring-data-commons-2.3.6.RELEASE.jar!/:2.3.6.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:550) ~[spring-data-commons-2.3.6.RELEASE.jar!/:2.3.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:155) ~[spring-data-commons-2.3.6.RELEASE.jar!/:2.3.6.RELEASE]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130) ~[spring-data-commons-2.3.6.RELEASE.jar!/:2.3.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80) ~[spring-data-commons-2.3.6.RELEASE.jar!/:2.3.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178) ~[spring-data-jpa-2.3.6.RELEASE.jar!/:2.3.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at com.sun.proxy.$Proxy89.saveAll(Unknown Source) ~[na:na]
        at com.ame.mihoyosign.service.RewardService.updateReward(RewardService.java:23) ~[classes!/:na]
        at com.ame.mihoyosign.service.MiHoYoService.updateYsRewards(MiHoYoService.java:99) ~[classes!/:na]
        at com.ame.mihoyosign.service.MiHoYoService.ysSign(MiHoYoService.java:113) ~[classes!/:na]
        at com.ame.mihoyosign.service.SignService.sign(SignService.java:53) ~[classes!/:na]
        at com.ame.mihoyosign.service.SignService.sign(SignService.java:32) ~[classes!/:na]
        at com.ame.mihoyosign.service.SignService$$FastClassBySpringCGLIB$$6567e409.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_291]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_291]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_291]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_291]

2021-07-16 06:30:08.192  WARN 7988 --- [         task-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 5, SQLState: null
2021-07-16 06:30:08.192 ERROR 7988 --- [         task-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : [SQLITE_BUSY]  The database file is locked (database is locked)
2021-07-16 06:30:08.232  INFO 7988 --- [         task-3] c.ame.mihoyosign.service.MessageService  : -->  QQ[23******19]  Message:[「签到 失败」 原因:error performing isolated work; nested exception is org.hibernate.exception.GenericJDBCException: error performing isolated work 游戏:原神 昵称:鹿 等级:56 UID:11******77 区服:天空岛]
2021-07-16 06:30:08.634  INFO 7988 --- [         task-4] c.ame.mihoyosign.service.MessageService  : 签到奖励列表已更新
2021-07-16 06:30:08.774  INFO 7988 --- [         task-2] c.ame.mihoyosign.service.MessageService  : -->  QQ[32******47]  Message:[「签到 成功」 奖励:精锻用良矿×5 [CQ:image,file=https://webstatic.mihoyo.com/upload/event/2020/09/29/174c57f4dfff99cc139fc7d9bc1ec866_2040518409571206704.png]游戏:原神 昵称:逐星之蝶 等级:55 UID:100******6 区服:天空岛]
2021-07-16 06:30:08.902  INFO 7988 --- [         task-4] c.ame.mihoyosign.service.MessageService  : -->  QQ[1053807086]  Message:[签到奖励列表已更新]
```

这是第二第三次的日志：

```
2021-07-17 06:30:07.134  WARN 10948 --- [         task-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 5, SQLState: null
2021-07-17 06:30:07.134 ERROR 10948 --- [         task-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : [SQLITE_BUSY]  The database file is locked (database is locked)
2021-07-17 06:30:07.174  INFO 10948 --- [         task-2] c.ame.mihoyosign.service.MessageService  : -->  QQ[32******47]  Message:[「签到 失败」 原因:could not extract ResultSet; nested exception is org.hibernate.exception.GenericJDBCException: could not extract ResultSet 游戏:原神 昵称:逐星之蝶 等级:55 UID:10*******6 区服:天空岛]
2021-07-17 06:30:07.399  INFO 10948 --- [         task-4] c.ame.mihoyosign.service.MessageService  : 签到奖励列表已更新


2021-07-17 10:00:58.574  INFO 6152 --- [nio-4440-exec-1] c.a.m.controller.MiraiWebSocket          : 已连接mirai
当前运行的线程名称：task-2
当前运行的线程名称：task-3
2021-07-18 06:30:08.431  WARN 6152 --- [         task-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 5, SQLState: null
2021-07-18 06:30:08.431 ERROR 6152 --- [         task-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : [SQLITE_BUSY]  The database file is locked (database is locked)
2021-07-18 06:30:08.593  INFO 6152 --- [         task-3] c.ame.mihoyosign.service.MessageService  : -->  QQ[23*******9]  Message:[「签到 失败」 原因:error performing isolated work; nested exception is org.hibernate.exception.GenericJDBCException: error performing isolated work 游戏:原神 昵称:鹿 等级:56 UID:11*********7 区服:天空岛]
2021-07-18 06:30:08.769  INFO 6152 --- [         task-4] c.ame.mihoyosign.service.MessageService  : 签到奖励列表已更新
2021-07-18 06:30:08.917  INFO 6152 --- [         task-2] c.ame.mihoyosign.service.MessageService  : -->  QQ[32*********7]  Message:[「签到 成功」 奖励:鸟蛋×3 [CQ:image,file=https://webstatic.mihoyo.com/upload/event/2020/09/29/3cd46753554c2e8642215ad58eff4f48_4044044587148145321.png]游戏:原神 昵称:逐星之蝶 等级:55 UID:10********6 区服:天空岛]
2021-07-18 06:30:09.039  INFO 6152 --- [         task-4] c.ame.mihoyosign.service.MessageService  : -->  QQ[1053807086]  Message:[签到奖励列表已更新]

```

**Comment by AMEKENN** [comment]
- The database file is locked 问题的确是这版本才加的多线程的问题，这几天会修的
- 通知问题，我是伞兵，重构代码的时候忘加判断了，导致这个值能修改，但就没用过，诶嘿
- 帮助亲测好的，改app.yml需要重启生效
- go-cqhttp我没测，不知道他临时消息参数怎样，修的时候测一下再看吧

谢谢，让我发现一堆bug，还有个不符合规范的日志
(ノ｀⊿´)ノ

**Comment by Mateoust** [comment]
> 谢谢，让我发现一堆bug，还有个不符合规范的日志
> (ノ｀⊿´)ノ

- app.yml我是重启过的。修改过一次我就重启过一次。但是就是没有生效。挺奇怪的 （后续我再试试吧，我之前是想改成发送图片，防止风控或者是合并发送这个api）

- 通知问题这个无论如何都会通知就有点麻烦吧。在不加好友的情况会多一些err的logs ・_・
- go-cqhttp的临时消息也是`/send_private_msg`不过要带上`group_id`这个参数。先前我也试过修改。不过不太懂导致了一些bug。我估计要将`group_id`存入数据库才行（￣～￣）在[go-cqhttp的api文档](https://docs.go-cqhttp.org/api/)中还有个`/send_msg`不知道这个会不会更方便实现一些？
- 还有`2021-07-18 06:30:09.039 INFO 6152 --- [ task-4] c.ame.mihoyosign.service.MessageService : --> QQ[1053807086] Message:[签到奖励列表已更新]`中的这个通知是否可以关闭呢？（注释掉那一段可以吧？）另外这个通知的QQ[1053807086]也不是bot的，是一个陌生的，弄不太明白为什么会这样[・ヘ・?]

不知道会不会和onebot mirai的master分支有冲突，开个分支是否会更好一些呢[・_・?]
